language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install now
script:
  - npm run lint
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  on: master
  script:
    - now -p --token=$NOW_TOKEN build && now alias --token=$NOW_TOKEN
